### ISSUE TITLE
好东西

### ISSUE THREAD

**Issue by byhc2** [Ovilia/biangua#5]
做得好，你对周易有兴趣？
浏览器兼容性怎么搞？IE8下面有报错，当然，IE很讨厌～～

**Comment by Ovilia** [comment]
嗯对，不明觉厉~
酷炫的东西就没想着调 IE，有什么建议？

**Comment by byhc2** [comment]
惭愧，我也只对html和css略知一二。看IE8的提示，貌似是因为less.js与ie8不兼容导致的。

---

消息: 对象不支持此属性或方法
行: 13
字符: 28000
代码: 0
URI: http://zhangwenli.com/biangua/js/less-1.7.3.min.js

**Comment by Ovilia** [comment]
明白啦，回头我看看~谢谢！
