### ISSUE TITLE
no thing i get from it

### ISSUE THREAD

**Issue by aaronwng** [Ovilia/biangua#6]
![Uploading Screen Shot 2015-06-27 at 11.15.57 PM.png…]()
chrome on mac appear this issue,is this a bug? nothing happen when i click the white bar. i've readding your blog, we are in common with interesting in Nature(Taoists more like a religion,i'd like to say Nature in english,it's where the things beginning,it's the truth),being a web artist,so appeal to chinese poem.Could we become friend? yuxianzhiyanai@163.com----my email.

**Comment by aaronwng** [comment]
chrome Version 39.0.2171.71 (64-bit)

**Comment by aaronwng** [comment]
![screen shot 2015-06-27 at 11 15 57 pm](https://cloud.githubusercontent.com/assets/9334435/8394770/458582a2-1d7a-11e5-9d30-eae58267e2f6.png)

**Comment by Ovilia** [comment]
I guess this is the problem caused by failing to get JSON data. You may see console for more information.
